# Generated by Django 6.1.1 on 2026-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_clientes_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
