# Generated by Django 6.1.1 on 2026-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cliente'),
        ),
    ]
