# Generated by Django 6.1.1 on 2026-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_clientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/foto_cliente'),
        ),
    ]
