# Generated by Django 6.1.1 on 2026-09-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('queixa', models.CharField(choices=[('D', 'Depressão'), ('A', 'Ansiedade')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/foto_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('possivel_causa', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.clientes')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sintomas')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='sintomas',
            field=models.ManyToManyField(through='usuarios.ClienteSintoma', to='usuarios.sintomas'),
        ),
    ]
