# Generated by Django 6.1.1 on 2026-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cliente'),
        ),
    ]
